### ISSUE TITLE
The requirements.txt should be changed to make Installation work.

### ISSUE THREAD

**Issue by CM-BF** [RexYing/gnn-model-explainer#15]
**Describe the bug**
File requirements.txt fault.

the last line of requirements.txt:
```
pywidgets==7.5.1
```
should be changed to:
```
ipywidgets==7.5.1
```
to make pip work or pip cannot find the package "pywidgets==7.5.1".

[Environment]
Anaconda3
pip 20.0.2
Ubuntu 18.04

**Comment by hnaik** [comment]
I submitted a PR @ https://github.com/RexYing/gnn-model-explainer/pull/19
