### ISSUE TITLE
Where is the dataset and what kind of dataset am I supposed to use inorder to train?

### ISSUE THREAD

**Issue by UniverseBorder** [RexYing/gnn-model-explainer#16]
sorry couldn‘t find them in the repository...

**Comment by hnaik** [comment]
If you scroll down to the bottom of the top-level README.md page, you'll see a table with hyperlinks. You should be able to click on the link, download the dataset, and unzip them inside your `data/` directory. It should all just work. 

For example, if you want to run the experiment for `Mutagenicity`
1. Go to https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets (as listed in the table)
2. Search for `Mutagenicity` on that page, which should allow you to download the data files from https://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets/Mutagenicity.zip
3. Unzip it inside your `data/` directory
4. Run `$ PYTHONPATH=. python train.py --bmname=Mutagenicity`
