### ISSUE TITLE
Request for pretrained models, as well as Tox21 dataset

### ISSUE THREAD

**Issue by Laksh1997** [RexYing/gnn-model-explainer#8]
**Describe the bug**
Please could we add pretrained models? I would love to play around with these. Also, could we add Tox21 dataset training possible please? 

Also - the visualisation page is down.

This is really great work - I don't mean to be complaining at all. Keep it up!

**To Reproduce**
`python train.py --dataset Tox21_AHR` does not work, as there is no config in `train.py` for the Tox21 dataset.

**Platform (please complete the following information):**
 - OS: Linux and Mac
 - Python 3.7
 - Version Latest

**Comment by dtsbourg** [comment]
Hi, 

The `Tox21` dataset can be downloaded [here](https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets). We currently don't have a plan to release pre-trained models as the results should be straightforward enough to reproduce but will discuss and come back to you if we do.
