### ISSUE TITLE
Error with virtualenv venv -p /usr/local/bin/python3

### ISSUE THREAD

**Issue by huynhtruc0309** [RexYing/gnn-model-explainer#9]
Hello, I am new to virtualenv. I have no idea why this has errors. Can anyone help me to resolve it?
![Capture](https://user-images.githubusercontent.com/37890714/75085365-fa1f6300-555a-11ea-8729-45f9e29a9343.PNG)

**Comment by dtsbourg** [comment]
Hi, It seems like an issue with your python installation. Check that Python is indeed installed at the specified path `/usr/local/bin/python3`. Since you're on Windows, I'd recommend taking a look at the installation guide [here](https://docs.python.org/3/using/windows.html). 

Hope it helps!
